In [17]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
## 表1数据处理
data1 = pd.read_excel("../竞赛发布数据/表1-患者列表及临床信息.xlsx")
data1 = data1.rename(columns={'Unnamed: 0': 'ID'})  # 使用 rename() 重命名列
data1 = data1.rename(columns={'入院首次影像检查流水号': '流水号'})  # 记得表1的流水号是 '首次影像检查流水号' 就行。

# 将 ID 为 'sub074' 的流水号改为 20180719000020
data1.loc[data1['ID'] == 'sub074', '流水号'] = 20180719000020
# 确保流水号列的格式为 int64
data1['流水号'] = data1['流水号'].astype('int64')

In [19]:
data1[data1['ID'] == 'sub074']

,ID,90天mRS,数据集划分,流水号,年龄,性别,脑出血前mRS评分,高血压病史,卒中病史,糖尿病史,...,饮酒史,发病到首次影像检查时间间隔,血压,脑室引流,止血治疗,降颅压治疗,降压治疗,镇静、镇痛治疗,止吐护胃,营养神经
73,sub074,0.0,训练,20180719000020,40,男,0,1,0,0,...,0,1.5,188/121,0,1,1,1,1,1,1

In [20]:
data1.to_csv("../处理后的数据/表1-患者列表及临床信息.csv", index=False)

在表1中，sub074的流水号有问题，已经修改了，或者按照ID合并

sub131		测试2	20160413000006

sub132		测试2	20161215001667

与

sub003	5 	训练	20160413000006

sub004	4 	训练	20161215001667

的流水号重复了

只能按照ID去合并了

In [21]:
## 数据格式也需要处理，后面再补充吧

In [22]:
## 表2数据处理
data2 = pd.read_excel('../竞赛发布数据/表2-患者影像信息血肿及水肿的体积及位置.xlsx')
df_data2 = pd.DataFrame(columns=["ID", "流水号"] + list(data2.iloc[:, 2:24].columns) + ["检查次序"])  # 创建一个空的 DataFrame
for i in range(9):
    temp = pd.DataFrame()
    temp = data2.iloc[:, 1+23*i:24+23*i]
    temp.columns = ['流水号'] + list(data2.iloc[:, 2:24].columns)
    # temp.rename(columns={temp.columns[0]: "随访流水号"}, inplace=True)
    temp['检查次序'] = i
    temp = pd.concat([data2["ID"], temp], axis = 1)
    temp = temp.dropna()  # 删除包含任何缺失值的行
    # 使用 concat 方法按行合并  # append在pandas1.4被标记，在2.0中被完全移除
    df_data2 = pd.concat([df_data2, temp], axis = 0, ignore_index=True)
df_data2['流水号'] = df_data2['流水号'].astype('int64')
df_data2.sort_values(by=['ID', '检查次序'], ascending=[True, True], inplace=True)
df_data2.to_csv("../处理后的数据/表2-血肿及水肿的体积及位置.csv", index=False)
df_data2

C:\Users\TCP\AppData\Local\Temp\ipykernel_35560\1626949825.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_data2 = pd.concat([df_data2, temp], axis = 0, ignore_index=True)

,ID,流水号,HM_volume,HM_ACA_R_Ratio,HM_MCA_R_Ratio,HM_PCA_R_Ratio,HM_Pons_Medulla_R_Ratio,HM_Cerebellum_R_Ratio,HM_ACA_L_Ratio,HM_MCA_L_Ratio,...,ED_MCA_R_Ratio,ED_PCA_R_Ratio,ED_Pons_Medulla_R_Ratio,ED_Cerebellum_R_Ratio,ED_ACA_L_Ratio,ED_MCA_L_Ratio,ED_PCA_L_Ratio,ED_Pons_Medulla_L_Ratio,ED_Cerebellum_L_Ratio,检查次序
0,sub001,20161212002136,69714,0.000258,0.877112,0.120148,0.000000,0.0,0.000000,0.000000,...,0.726241,0.136511,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0
160,sub001,20161213000009,74902.0,0.000360,0.869683,0.126018,0.000000,0.0,0.000000,0.000000,...,0.782998,0.093406,0.000259,0.0,0.000000,0.000000,0.000000,0.000000,0.0,1
290,sub001,20161218000100,70952.0,0.001550,0.817059,0.165718,0.000000,0.0,0.000000,0.000000,...,0.681799,0.149608,0.005285,0.0,0.000000,0.000000,0.000000,0.000000,0.0,2
414,sub001,20161223001020,62831.0,0.004663,0.803505,0.177158,0.000048,0.0,0.000000,0.000000,...,0.599000,0.141892,0.015576,0.0,0.000000,0.000000,0.000000,0.000000,0.0,3
502,sub001,20161230000574,44029.0,0.000341,0.835563,0.154784,0.000000,0.0,0.000000,0.000000,...,0.669171,0.127009,0.015203,0.0,0.000000,0.000000,0.000016,0.000000,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,sub158,20200423000871,3647.0,0.000000,0.957499,0.042501,0.000000,0.0,0.000000,0.000000,...,0.820977,0.102937,0.001634,0.0,0.000000,0.000000,0.000000,0.000000,0.0,3
158,sub159,20200218000582,53154,0.000000,0.000000,0.000000,0.000000,0.0,0.004572,0.857678,...,0.000000,0.000000,0.000000,0.0,0.147678,0.711019,0.124740,0.008247,0.0,0
288,sub159,20200219000588,126642.0,0.004967,0.000174,0.003774,0.000000,0.0,0.086038,0.743292,...,0.001735,0.022767,0.005153,0.0,0.278195,0.286345,0.240602,0.025028,0.0,1
159,sub160,20200821002584,49019,0.000000,0.907505,0.092372,0.000000,0.0,0.000000,0.000000,...,0.679948,0.066373,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0
289,sub160,20200822000947,100470.0,0.031064,0.827919,0.119339,0.000000,0.0,0.000000,0.000000,...,0.411951,0.179479,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,1

In [23]:
df_data2.dtypes

ID                          object
流水号                          int64
HM_volume                   object
HM_ACA_R_Ratio             float64
HM_MCA_R_Ratio             float64
HM_PCA_R_Ratio             float64
HM_Pons_Medulla_R_Ratio    float64
HM_Cerebellum_R_Ratio      float64
HM_ACA_L_Ratio             float64
HM_MCA_L_Ratio             float64
HM_PCA_L_Ratio             float64
HM_Pons_Medulla_L_Ratio    float64
HM_Cerebellum_L_Ratio      float64
ED_volume                   object
ED_ACA_R_Ratio             float64
ED_MCA_R_Ratio             float64
ED_PCA_R_Ratio             float64
ED_Pons_Medulla_R_Ratio    float64
ED_Cerebellum_R_Ratio      float64
ED_ACA_L_Ratio             float64
ED_MCA_L_Ratio             float64
ED_PCA_L_Ratio             float64
ED_Pons_Medulla_L_Ratio    float64
ED_Cerebellum_L_Ratio      float64
检查次序                        object
dtype: object

In [24]:
## 表3数据处理

# ED代表水肿，HM代表血肿
data3_ED = pd.read_excel("../竞赛发布数据/表3-患者影像信息血肿及水肿的形状及灰度分布.xlsx", sheet_name="ED")
data3_ED.drop(columns="备注", inplace=True)
data3_ED_columns = ["流水号"]
for i in range(1, len(list(data3_ED.columns))):
    data3_ED_columns.append("ED_" + data3_ED.columns[i])
data3_ED.columns = data3_ED_columns

data3_HM = pd.read_excel("../竞赛发布数据/表3-患者影像信息血肿及水肿的形状及灰度分布.xlsx", sheet_name="Hemo")
data3_HM.drop(columns="备注", inplace=True)
data3_HM_columns = ["流水号"]
for i in range(1, len(list(data3_ED.columns))):
    data3_HM_columns.append("HM_" + data3_HM.columns[i])
data3_HM.columns = data3_HM_columns

data3_ED.to_csv("../处理后的数据/表3_水肿的形状及灰度分布_ED.csv", index=False)
data3_HM.to_csv("../处理后的数据/表3_血肿的形状及灰度分布_HM.csv", index=False)

In [25]:
### 附表1-时间点-流水号数据处理

time_data = pd.read_excel("../竞赛发布数据/附表1-检索表格-流水号vs时间.xlsx")  # 流水号、ID、时间对照表
df_time_number = pd.DataFrame(columns=['ID', '重复次数','随访时间点', '流水号', '检查次序'])
for i in range(14):
    temp0 = pd.DataFrame(columns=['随访时间点', '流水号', '检查次序'])
    temp0[["随访时间点", "流水号"]] = time_data.iloc[:, [2+2*i, 2+2*i+1]]
    # 添加一列数字表示第几次检查
    temp0['检查次序'] = i
    temp = pd.concat([time_data[["ID", "重复次数"]], temp0], axis = 1)
    # temp.columns = ["ID", "重复次数", "随访时间点", "随访流水号", "检查次序"]
    temp = temp.dropna()  # 删除包含任何缺失值的行
    df_time_number = pd.concat([df_time_number, temp], axis = 0, ignore_index=True)

df_time_number.to_csv("../处理后的数据/附表1-时间点-流水号.csv", index=False)
df_time_number

C:\Users\TCP\AppData\Local\Temp\ipykernel_35560\1696972757.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_time_number = pd.concat([df_time_number, temp], axis = 0, ignore_index=True)
C:\Users\TCP\AppData\Local\Temp\ipykernel_35560\1696972757.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_time_number = pd.concat([df_time_number, temp], axis = 0, ignore_index=True)

           ID 重复次数               随访时间点               流水号 检查次序
0    Hemo0001    5 2016-12-12 23:32:54    20161212002136    0
1    Hemo0002    5 2016-04-06 21:21:03    20160406002131    0
2    Hemo0004    3 2016-04-13 01:18:17    20160413000006    0
3    Hemo0006    4 2016-12-15 22:53:41    20161215001667    0
4    Hemo0012    3 2016-12-22 13:18:48    20161222000978    0
..        ...  ...                 ...               ...  ...
657  Hemo0483   13 2018-01-26 09:57:26  20180126000567.0    8
658  Hemo0483   13 2018-02-01 10:32:30  20180201000828.0    9
659  Hemo0483   13 2018-02-13 09:48:21  20180213000362.0   10
660  Hemo0483   13 2018-03-16 15:38:42  20180316001622.0   11
661  Hemo0483   13 2018-12-02 11:10:44  20181202000350.0   12

[662 rows x 5 columns]

In [26]:
## 表1数据处理
data1 = pd.read_excel("../竞赛发布数据/表1-患者列表及临床信息.xlsx")
data1 = data1.rename(columns={'Unnamed: 0': 'ID'})  # 使用 rename() 重命名列
data1 = data1.rename(columns={'入院首次影像检查流水号': '流水号'})  # 记得表1的流水号是 '首次影像检查流水号' 就行。
data1.drop(columns=['90天mRS'], inplace=True)
## 表2数据处理
data2 = pd.read_excel('../竞赛发布数据/表2-患者影像信息血肿及水肿的体积及位置.xlsx')
data2.columns

Index(['ID', '首次检查流水号', 'HM_volume', 'HM_ACA_R_Ratio', 'HM_MCA_R_Ratio',
       'HM_PCA_R_Ratio', 'HM_Pons_Medulla_R_Ratio', 'HM_Cerebellum_R_Ratio',
       'HM_ACA_L_Ratio', 'HM_MCA_L_Ratio',
       ...
       'ED_ACA_R_Ratio.8', 'ED_MCA_R_Ratio.8', 'ED_PCA_R_Ratio.8',
       'ED_Pons_Medulla_R_Ratio.8', 'ED_Cerebellum_R_Ratio.8',
       'ED_ACA_L_Ratio.8', 'ED_MCA_L_Ratio.8', 'ED_PCA_L_Ratio.8',
       'ED_Pons_Medulla_L_Ratio.8', 'ED_Cerebellum_L_Ratio.8'],
      dtype='object', length=208)

In [27]:
data1.columns

Index(['ID', '数据集划分', '流水号', '年龄', '性别', '脑出血前mRS评分', '高血压病史', '卒中病史', '糖尿病史',
       '房颤史', '冠心病史', '吸烟史', '饮酒史', '发病到首次影像检查时间间隔', '血压', '脑室引流', '止血治疗',
       '降颅压治疗', '降压治疗', '镇静、镇痛治疗', '止吐护胃', '营养神经'],
      dtype='object')

In [28]:
data2 = data2[["ID", "首次检查流水号"]]
data2.columns = ["ID", "流水号"]
data1.shape, data2.shape

((160, 22), (160, 2))

In [29]:
df = pd.merge(data1, data2, on='ID', how='left')
print(df.shape)
df.head()

(160, 23)

,ID,数据集划分,流水号_x,年龄,性别,脑出血前mRS评分,高血压病史,卒中病史,糖尿病史,房颤史,...,发病到首次影像检查时间间隔,血压,脑室引流,止血治疗,降颅压治疗,降压治疗,镇静、镇痛治疗,止吐护胃,营养神经,流水号_y
0,sub001,训练,20161212002136,43,女,0,0,0,0,0,...,2.5,180/90,0,1,1,1,1,1,1,20161212002136
1,sub002,训练,20160406002131,58,男,0,1,0,0,0,...,3.0,199/120,0,1,1,1,0,1,1,20160406002131
2,sub003,训练,20160413000006,78,男,0,1,0,0,0,...,2.0,199/120,0,1,1,1,1,1,1,20160413000006
3,sub004,训练,20161215001667,70,男,2,1,1,0,0,...,1.0,186/99,0,1,1,1,0,0,0,20161215001667
4,sub005,训练,20161222000978,51,男,0,0,0,0,0,...,5.0,135/92,0,1,1,0,0,1,1,20161222000978

In [30]:
# 打印空行
rows_with_na = df[df.isna().any(axis=1)]
rows_with_na

Empty DataFrame
Columns: [ID, 数据集划分, 流水号_x, 年龄, 性别, 脑出血前mRS评分, 高血压病史, 卒中病史, 糖尿病史, 房颤史, 冠心病史, 吸烟史, 饮酒史, 发病到首次影像检查时间间隔, 血压, 脑室引流, 止血治疗, 降颅压治疗, 降压治疗, 镇静、镇痛治疗, 止吐护胃, 营养神经, 流水号_y]
Index: []

[0 rows x 23 columns]

In [31]:
df = pd.merge(data1, data2, on='流水号', how='left')
print(df.shape)
df.head()

(160, 23)

,ID_x,数据集划分,流水号,年龄,性别,脑出血前mRS评分,高血压病史,卒中病史,糖尿病史,房颤史,...,发病到首次影像检查时间间隔,血压,脑室引流,止血治疗,降颅压治疗,降压治疗,镇静、镇痛治疗,止吐护胃,营养神经,ID_y
0,sub001,训练,20161212002136,43,女,0,0,0,0,0,...,2.5,180/90,0,1,1,1,1,1,1,sub001
1,sub002,训练,20160406002131,58,男,0,1,0,0,0,...,3.0,199/120,0,1,1,1,0,1,1,sub002
2,sub003,训练,20160413000006,78,男,0,1,0,0,0,...,2.0,199/120,0,1,1,1,1,1,1,sub003
3,sub004,训练,20161215001667,70,男,2,1,1,0,0,...,1.0,186/99,0,1,1,1,0,0,0,sub004
4,sub005,训练,20161222000978,51,男,0,0,0,0,0,...,5.0,135/92,0,1,1,0,0,1,1,sub005

In [32]:
# 打印空行
rows_with_na = df[df.isna().any(axis=1)]
rows_with_na

,ID_x,数据集划分,流水号,年龄,性别,脑出血前mRS评分,高血压病史,卒中病史,糖尿病史,房颤史,...,发病到首次影像检查时间间隔,血压,脑室引流,止血治疗,降颅压治疗,降压治疗,镇静、镇痛治疗,止吐护胃,营养神经,ID_y
73,sub074,训练,20180719000630,40,男,0,1,0,0,0,...,1.5,188/121,0,1,1,1,1,1,1,NaN